apiVersion: v1
kind: Config
clusters:
- name: "frontcluster"
  cluster:
    server: "https://ec2-52-90-172-160.compute-1.amazonaws.com/k8s/clusters/c-7pjfh"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpOVEExTVRneU9UUXlXaGNOTXpJd05UQXlNVGd5T1RReVdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNZQTdnbXBUdlo5a\
      EN4TVQrTHFXcjV0cHRMcUNnM0JrYjIvQStBZ2ZVdAowL1Y1R2tweHVBYWdtcGUwaW03WHRid1U3c\
      jlwQ1FtNzZacUpRbUlaNzA0UG8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUUFNZ3JqcUFyNk5YVlpKdjVwRUQKaXlkWGYzNHdDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWdYNmV5czB4ZmY4VVU4M3lWQlN1REpIMncwVHF6YmJxbQp3c\
      UdFY1ExOXZnd0NJUURJSEdCSVlwbDNQS0JWTHJHRVhSMldTcjViWExNaWNiMWhNQ21HS3UvcVBRP\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "frontcluster-fronttempprefix1"
  cluster:
    server: "https://54.89.149.205:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURVd05qQTFNamN5T1ZvWERUTXlNRFV3TXpBMU1qY3lPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUw1ZHlkNyt0ckpTCkx4THRvOEZOOEg0a0p0czdQMk0xenRYM00zMTlSMGJxTHFuRFVGT3NwU\
      3JPREJPN2dEVmtMSVgvT3daZkU5czAKVGJKMjJxT1VrZ1U5cWZqSFQ0dHF0UE00T0NWVGYvaEJZd\
      UdqVEQwa1U5Z0RIVXMxSXEvQjJhdU5YMU5kd3V4MgpYRTJRcTYrVmp5WXNVTTM0YkFUSjVqeXdHU\
      WFha2hYT1BpTHJmNGV2SVVBcEVvS1A1MkhNUmNMc2MvR3BQc0ZPCnBJSnp2emRHY1RxWEJsNk1YQ\
      3VCWTZQVzhTQ042WmFZbldmSEdmY3R1Um05NWN1OEI3NmVJUnNHMFRVaExFcHYKNDNOOEU5YXkzM\
      VcvNFNRcDY3dVNhM3pPMjdrQ2QyK0hGc3NJNkFQVnJiclFxL1RLTXk1aDFpa0pteU4ycVBtUgpWW\
      GU4RytFRmlKa0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGT1JlSWZvQ0Z4OFVCQ0V5S0hFdVFMVHREczBwTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQkFVaXZONGV2Z2VHTWFJbUczdXFGY0lhSFJJQU5BS2tiOTNCS\
      01Xc28rVkptd1l4eFY0QVNoSHRRVQpRMWR2d1NnZm5WM1kxR2ZUM0lDb3lnSnZvaTF2Y0RQa0NnQ\
      nF6WlVVa3NxT1FBRTdva2ZybkNVUVhaZW5BemZlCllYVWZaMkgyOFlZRW1Zck8wL0VXUXM1eHhPb\
      XowbFBOTlFwRU5TSDMzUUVQejhpL3h6YzJjb2JBVS9mZmdOM2gKM2dHK1VoNVNyV1YrZXFicXhLc\
      HIzV2lGMGJoZzF6QWtCbkZiZkRHUk9FdEdYT0NCdWc2S2VnZ3cvSlhVTENkOQpOS2FYMDM5YzR3N\
      ldjYnc3RW5mMzdrdXJWQUdPRW1MT0hxVHpTeHhoeDZQRVBEZEdVODljRnE0anl5K2U3dDBtCmxGN\
      0hka0xjM1o2cWREcDZvdnY5ZWNpZ0toY2YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "frontcluster"
  user:
    token: "kubeconfig-user-vk4wq2tmnd:mst9vtnntwn7kwfzxq9dmflbfv6z5jrnp4c5c5ndh5n85ltk8jbc2s"


contexts:
- name: "frontcluster"
  context:
    user: "frontcluster"
    cluster: "frontcluster"
- name: "frontcluster-fronttempprefix1"
  context:
    user: "frontcluster"
    cluster: "frontcluster-fronttempprefix1"

current-context: "frontcluster"
